# Generated by Django 4.2 on 2023-05-30 16:16

from django.db import migrations, models
import django.db.models.deletion
import jazigo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cemiterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cemiterio', models.CharField(max_length=100)),
                ('endereco_cemiterio', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Concessionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_concessionaro', models.CharField(max_length=100)),
                ('cpf_concessionario', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='QuadraESepultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadra', models.CharField(max_length=10)),
                ('sepultura', models.IntegerField()),
                ('complemento', models.CharField(blank=True, default=' ', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaDeOssada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel_translado', models.CharField(max_length=100)),
                ('documento_responsavel_translado', models.CharField(max_length=100)),
                ('cemiterio_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cemiterio_origem', to='jazigo.cemiterio')),
                ('jazigo_cemiterio_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cemiterio_destino', to='jazigo.cemiterio')),
            ],
        ),
        migrations.CreateModel(
            name='Sepultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sepultado', models.CharField(max_length=100)),
                ('data_falecimento', models.DateField()),
                ('certidao_obito', models.FileField(blank=True, null=True, upload_to=jazigo.models.Sepultado.pasta_de_upload)),
                ('guia_sepultamento', models.FileField(blank=True, null=True, upload_to=jazigo.models.Sepultado.pasta_de_upload)),
                ('termo_concessao_jazigo_perpetuo', models.FileField(blank=True, null=True, upload_to=jazigo.models.Sepultado.pasta_de_upload)),
                ('recibo_pagamento', models.FileField(blank=True, null=True, upload_to=jazigo.models.Sepultado.pasta_de_upload)),
                ('transferencia_restos_mortais', models.FileField(blank=True, null=True, upload_to=jazigo.models.Sepultado.pasta_de_upload)),
                ('sepultamento_externo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jazigo.cemiterio')),
                ('transferencia_ossada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazigo.transferenciadeossada')),
            ],
        ),
        migrations.CreateModel(
            name='Jazigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidade_urnas', models.IntegerField()),
                ('jazigo_privado_publico', models.CharField(choices=[('Público', 'publico'), ('Privado', 'privado')], max_length=100)),
                ('observacao', models.TextField(null=True)),
                ('identificacao_jazigo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jazigo.quadraesepultura')),
                ('nome_concessionaro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jazigo.concessionario')),
                ('nome_sepultado', models.ManyToManyField(to='jazigo.sepultado')),
            ],
        ),
    ]
