# Generated by Django 4.2 on 2023-06-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazigo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferenciadeossada',
            old_name='jazigo_cemiterio_destino',
            new_name='cemiterio_destino',
        ),
        migrations.RemoveField(
            model_name='jazigo',
            name='capacidade_urnas',
        ),
        migrations.RemoveField(
            model_name='jazigo',
            name='jazigo_privado_publico',
        ),
        migrations.RemoveField(
            model_name='sepultado',
            name='sepultamento_externo',
        ),
        migrations.AddField(
            model_name='concessionario',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concessionario',
            name='telefone',
            field=models.CharField(default=1111111111, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jazigo',
            name='jazigo_perpetuo_publico',
            field=models.CharField(choices=[('Público', 'publico'), ('Perpétuo', 'perpetuo')], default='perpetuo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sepultado',
            name='local_sepultamento',
            field=models.CharField(choices=[('Piraí', 'pirai'), ('Santanésia', 'santanesia'), ('Cacaria', 'cacaria'), ('Arrozal', 'arrozal'), ('Externo', 'externo')], default='santanesia', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jazigo',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sepultado',
            name='transferencia_ossada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazigo.cemiterio'),
        ),
    ]
